### ISSUE TITLE
load_pretrained_wordembedding函数中+pad和unk处报错

### ISSUE THREAD

**Issue by ShinCYZhou** [jeffery0628/text_classification#2]
Word2VecKeyedVectors没有add属性

**Comment by jeffery0628** [comment]
出现这个错误的原因可能是因为你所使用的词向量的格式与我使用的格式不一致，我是在https://github.com/Embedding/Chinese-Word-Vectors 上面下载的sgns.sogou.char 300d 的词向量。可以根据自己词向量格式，适当修改load_pretrained_wordembedding中关于词向量的加载方式。
